from setuptools import setup, find_packages
from lisereader.version import __version__

long_description = ''

try:
    from pypandoc import convert_file

    read_md = lambda f: convert_file(f, 'rst', 'md')
except ImportError:
    print("warning: pypandoc module not found, could not convert Markdown to RST")
    read_md = lambda f: open(f, 'r').read()

classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: Physics'
]

setup(
    name='LISEreader',
    packages=find_packages(),
    version=__version__,
    description='Reader of data files generated by LISE++.',
    long_description=read_md('README.md'),
    author='gwgwhc',
    url='https://github.com/gwgwhc/lisereader',
    download_url=f'https://github.com/gwgwhc/lisereader/tarball/{__version__}',
    entry_points={
        'console_scripts': [
            'lisereader = lisereader.__main__:main'
        ]
    },
    license='GPLv3',
    keywords=['physics', 'data', 'LISE++', ],
    classifiers=classifiers
)
