from setuptools import setup, find_packages
from lisereader.version import __version__
from pathlib import Path

this_directory = Path(__file__).parent
long_description = (this_directory / 'README.md').read_text()

classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: Physics'
]

setup(
    name='LISEreader',
    packages=find_packages(),
    version=__version__,
    description='Reader of data files generated by LISE++.',
    long_description=long_description,
    long_description_content_type='text/markdown',
    author='gwgwhc',
    url='https://github.com/gwgwhc/lisereader',
    download_url=f'https://github.com/gwgwhc/lisereader/tarball/{__version__}',
    entry_points={
        'console_scripts': [
            'lisereader = lisereader.__main__:main'
        ]
    },
    license='GPLv3',
    keywords=['physics', 'data', 'LISE++', ],
    classifiers=classifiers
)
